class Student < ActiveRecord::Base
  attr_accessible :address_1, :address_2, :city, :first_name, :last_name, :phone, :state, :zip
  validates_presence_of :first_name, :last_name, :address_1, :city, :message => "must be provided!"
  validates_inclusion_of :state, :in => [ 'AL',
 'AK',
 'AZ',
 'AR',
 'CA',
 'CO',
 'CT',
 'DE',
 'FL',
 'GA',
 'HI',
 'ID',
 'IL',
 'IN',
 'IA',
 'KS',
 'KY',
 'LA',
 'ME',
 'MD',
 'MA',
 'MI',
 'MN',
 'MS',
 'MO',
 'MT',
 'NE',
 'NV',
 'NH',
 'NJ',
 'NM',
 'NY',
 'NC',
 'ND',
 'OH',
 'OK',
 'OR',
 'PA',
 'RI',
 'SC',
 'SD',
 'TN',
 'TX',
 'UT',
 'VT',
 'VA',
 'WA',
 'WV',
 'WI',
 'WY'], :message => " must be a valid two character state abbreviation!"
  validates_length_of :zip, :minimum => 5, :maximum => 5, :message => " Code must be five digits!"
  validates_format_of :phone, :with => /\d{3}-\d{3}-\d{4}/, :message => " must be entered in the xxx-xxx-xxxx format!"
end
